name: tests

on:
  push:
  pull_request:
  workflow_dispatch:
    # Allow to run manually

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cargo:
    if: ${{ false }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          - '3.14'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: rustup override set nightly
      - run: cargo build -vv

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          # PyO3 0.29 supports Python 3.8 and later, however, building
          # Rust extension modules requires Meson 1.12 or later, which
          # requires Python 3.10.
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
          - '3.15'
          - '3.15t'
          - 'pypy3.11'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - run: rustup override set nightly
      - run: python -m pip install -v . -Ccompile-args=-v
      - run: python -m unittest -v test.py
